pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Run Maven build inside the Docker container
        sh 'mvn clean install'
        sh 'mvn --version'
      }
    }
  }
}
